name: Trigger

on: 
  workflow_dispatch:
    secrets:
      E2E_TESTS_PAT:
        required: true
      TESTING:
        required: true

jobs:
  trigger-job:
    name: 'Trigger job'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This is the TRIGGER workflow -- TESTING -> ${{ secrets.TESTING }}".'
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.E2E_TESTS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OasisDEX/e2e-tests/dispatches \
            -d "{\"event_type\":\"dispatch-event\"}"

  # trigger:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Trigger Workflow in Another Repository
  #       run: |
  #         # Set the required variables
  #         repo_owner="REPOSITORY OWNER" 
  #         repo_name="REPOSITORY NAME"  
  #         event_type="trigger-workflow" 
  #         service=${{ github.event.inputs.target_service }}"
  #         version="${{ github.event.inputs.target_version }}"
  
  #         curl -L \
  #           -X POST \
  #           -H "Accept: application/vnd.github+json" \
  #           -H "Authorization: Bearer ${{ secrets.PAT }}" \
  #           -H "X-GitHub-Api-Version: 2022-11-28" \
  #           https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
  #           -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"

  #         curl -X POST \
  #           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  #           https://api.github.com/repos/owner/repo/dispatches/events \
  #           -d '{"event_type": "my_event"}'

  #         curl -L \
  #           -X POST \
  #           -H "Accept: application/vnd.github+json" \
  #           -H "Authorization: Bearer <YOUR-TOKEN>" \
  #           -H "X-GitHub-Api-Version: 2022-11-28" \
  #           https://api.github.com/repos/<OWNER>/<REPO>/dispatches \
  #           -d '{"event_type":"<EVENT-TYPE>"}'