name: Trigger

on: 
  workflow_dispatch:
    secrets:
      E2E_TESTS_PAT:
        required: true
      TESTING:
        required: true

jobs:
  trigger-job:
    name: 'Trigger job'
    runs-on: ubuntu-latest
    env:
      TESTING: ${{ secrets.TESTING }}
      E2E_TESTS_PAT: ${{ secrets.E2E_TESTS_PAT }}
    steps:
      - run: echo 'This is the TRIGGER workflow -- TESTING -> ${{ secrets.TESTING }}".'
      - name: Trigger Workflow in Another Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.E2E_TESTS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OasisDEX/e2e-tests/dispatches \
            -d "{\"event_type\":\"dispatch-event\", \"client_payload\": {\"service\": \"e2e-tests\", \"version\": \"v1.0.1\", \"unit\": false, \"integration\": true}}"
