name: Regression E2E tests

on: 
  workflow_dispatch:
    secrets:
      E2E_TESTS_PAT:
        required: true

jobs:
  e2e-tests:
    name: 'Regression E2E tests'
    runs-on: ubuntu-latest
    env:
      E2E_TESTS_PAT: ${{ secrets.E2E_TESTS_PAT }}
    steps:
      - run echo 'RUN ID is ${{ github.run_id }} --'
      - name: Triggering regression e2e tests in e2e-test repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.E2E_TESTS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OasisDEX/e2e-tests/actions/workflows/ci_e2e_tests.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\":{\"name\":\"Mona the Octocat\"}}"
      - run: echo 'See test results in https://github.com/OasisDEX/e2e-tests/actions/workflows/ci_e2e_tests.yml'

